### ISSUE TITLE
El código de prueba no debería estar mezclado con el de producción

### ISSUE THREAD

**Issue by evolentini** [MtinDuarte/12_TSSE#2]
No hay ninguna razón para que estas dos declaraciones

https://github.com/MtinDuarte/12_TSSE/blob/40c996684b0ba9e2db84156616328666ceb509b0/TP3_vsA/src/leds.h#L11-L12

estén el en archivo `leds.h` en lugar de en el mismo archivo `test_leds.c`

**Comment by MtinDuarte** [comment]
Lo había puesto así, debido a que quería dejar macros en los test también y test_leds.c también apunta a leds.h 
En los test, ¿ Es correcto que quede de la siguiente manera ? 
const uint8_t onOffLed = 5; 
const uint8_t onLed       = 2;

**Comment by evolentini** [comment]
No hay nada que impida poner un `#define` en un archivo `.c`, por lo tanto podes hacerlo con constantes como propones o simplemente mover los defines a la parte de arriba del archivo `test_leds.c `. No hay necesidad de que los macros estén en un archivo  `.h`, solo se colocan ahí cuando se usan desde más de un lugar .
