### ISSUE TITLE
Las pruebas deben ser automáticas

### ISSUE THREAD

**Issue by evolentini** [MtinDuarte/12_TSSE#4]
La generación de las condiciones de prueba y la evaluación de los resultados debe efectuarse en forma automática, si una persona debe evaluar un resultado (o lo cambiar el valor de una prueba), entonces no tenemos pruebas automáticas

https://github.com/MtinDuarte/12_TSSE/blob/40c996684b0ba9e2db84156616328666ceb509b0/TP3_vsA/test/test_leds.c#L53

Estas pruebas deben desdoblarse en dos: una que prueba el caso correcto y otra que prueba el caos incorrecto.

**Comment by MtinDuarte** [comment]
Creo que comprendí lo del primer párrafo. ¿Lo soluciono eliminando la macro y colocando el número de LED a testear para que se condiga con el resultado de la prueba. 
La otra parte no la comprendí:

> Estas pruebas deben desdoblarse en dos: una que prueba el caso correcto y otra que prueba el caos incorrecto.

No entiendo muy bien a qué hace referencia esto.  Tengo el test de `test_turnLedOn` y `test_turnOneLedOff`

**Comment by evolentini** [comment]
Me refiero al `if` que esta después

https://github.com/MtinDuarte/12_TSSE/blob/40c996684b0ba9e2db84156616328666ceb509b0/TP3_vsA/test/test_leds.c#L54

si no entiendo mal ese `if` esta porque en un momento corriste la prueba con un led valido y después cambiaste el led por un invalido. Eso deberían ser dos pruebas diferentes y no una con un `if`. Se entendió ahora? Eso aplica a todas las pruebas que tienen ese `if`, es decir casi todas.

**Comment by evolentini** [comment]
para que quede mas claro, esto

https://github.com/MtinDuarte/12_TSSE/blob/40c996684b0ba9e2db84156616328666ceb509b0/TP3_vsA/test/test_leds.c#L51-L63

se debería reemplazar por eso

```c
void test_turnLedOnValid(void)
{
	const uint8_t testLed = 2;
	TEST_ASSERT_TRUE(turnLedOn(testLed));
	TEST_ASSERT_EQUAL_UINT16(0b0000000000000010 , ledPort);
}

void test_turnLedOnInvalid(void)
{
	const uint8_t testLed = 17;
	TEST_ASSERT_FALSE(turnLedOn(testLed));
}
```
