### ISSUE TITLE
¿Cual es el objetivo de estas definiciones?

### ISSUE THREAD

**Issue by evolentini** [MtinDuarte/12_TSSE#8]
No entiendo el objetivo definir un macro para deshabilitar una prueba. En primer lugar se deberían correr todas las pruebas siempre, y en segundo lugar ese archivo de configuración de las pruebas no debería estar con el código de producción

https://github.com/MtinDuarte/12_TSSE/blob/597dcab7bd05effcbcdeadad82a10703e968b834/TP3_vsA/src/config.h#L9-L16

**Comment by MtinDuarte** [comment]
Consideré que podía ser de ayuda en caso de que se quiera probar sólo algunos test, o en el caso de que alguna prueba rompa con las demás, pueda servir de ayuda. 
Podría sacarlo, pero me gustaría dejarlo si es posible. 

> en segundo lugar ese archivo de configuración de las pruebas no debería estar con el código de producción

¿Debería estar en una carpeta inc/ por ejemplo?

**Comment by evolentini** [comment]
Es tu código, así que no me voy a oponer, pero realmente complica mucho la legibilidad del código. Las alternativas que se me ocurren son usar la funcionalidad que incluye el framework con el macro `TEST_IGNORE()` que podrías usar. La otra posibilidad seria definir un macro para eliminar los #if del código. Y si lo vas. dejar tal como esta, entonces esos define deberían estar directamente al inicio del archivo de Testing, no hace falta que estén en una cabecera.

No es obligación poner los macros en una cabecera, solo se los pone ahí cuando se usan en más de un archivo, sino se ponen directamente en el archivo `.c` que los necesita.

**Comment by MtinDuarte** [comment]
Ok Esteban, los voy a sacar. En cuanto a las demás correcciones ¿están ok?
